# PerWorldPlugins Configuration

# Disable or Enable the message of new updates.
updateChecker: true
# Disable or Enable the bStats metrics.
metrics: true
# Message send when execute blocked plugin command.
disabledCommandMessage: "&4[Server]: &f{player} this command is disabled for {world}."

# If false, the plugins/groups added in the world will work.
# If true, it will be reversed.
blacklist: true

plugins:
  # For set group set - g:example (example is the name of group)
  # Add and edit groups in the groups.yml
  # ":ignore" is for ignore this plugin and don't check this.
  # In the Example case, the plugin is blocked in "world" (If is the blacklist on true)
  Example:
    - "world"
