# PerWorldPlugins Configuration

# Disable or Enable the message of new updates.
updateChecker: true
# Disable or Enable the bStats metrics.
metrics: true
# Message send when execute blocked plugin command.
disabledCommandMessage: "&4[Server]: &fThis command is disabled for this world."

# If false, the plugins/groups added in the world will work.
# If true, it will be reversed.
blacklist: true

plugins:
  # For set group set - g:example (example is the name of group)
  # Add and edit groups in the groups.yml
  Example:
    - "PutWorldInThisListForDisableThisPluginOnWorld"
    - "world"
  Example2:
    # ":ignore" is for ignore this plugin and don't check this.
    - "ignore:"