name: Build and Upload Artifacts
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 8

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: PerWorldPlugins
          path: build/libs/**.jar